# Generated by Django 3.1.2 on 2020-10-10 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20201007_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pedalboard',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedalboard',
            name='color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pedalboard',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('pedalboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pedalboard')),
            ],
        ),
        migrations.AddField(
            model_name='pedalboard',
            name='pedals',
            field=models.ManyToManyField(to='main_app.Pedal'),
        ),
    ]
